### PR TITLE
Upgrade Starscream dependency to version 4.

### PR DESCRIPTION
**Pull request by DtechLabs**

### CODE REVIEW

**Review by DmitryBespalov — APPROVED** [review]
looks good

**Comment by sche** [comment]
I will merge after some testing tomorrow

**Review by sche — CHANGES_REQUESTED** [review]
@DtechLabs sorry for the delayed response. 
I am trying to run a server test app (you need to add a missing delegate method with an empty body to make it run) and I can't establish a new connection with https://example.walletconnect.org/

In logs I can see `WC: ==> unhandled event: viabilityChanged(true)` and `WC: ==> error: WSError(type: Starscream.ErrorType.securityError, message: "accept header doesn\'t match", code: 1)`
Could you try to run it on your side and fix client and server test apps in your PR, please?

**Comment by DtechLabs** [comment]
Hmm.  Ok. I'll check it tommorow

**Comment by tracy-e** [comment]
Hi, I want to know the progress of this pr, thx.

**Comment by DtechLabs** [comment]
@sche Hi. Sorry I was overhead last days.  So I found the solution to the Demo ServerApp problem, but not sure if it should be in the package

if we change `WebSocket(request: URLRequest(url: url.bridgeURL)` to the next =>
`
      socket = WebSocket(
          request: URLRequest(url: url.bridgeURL),
          engine: WSEngine(transport: FoundationTransport(), certPinner: FoundationSecurity(allowSelfSigned: true))
      )
`

in `WebSocketConnection.swift: ` - it works.

What do you think?

**Comment by sche** [comment]
Hi @DtechLabs 
I have several comments.
- I think we should bypass `allowSelfSigned: Bool` to initialiser of Client and Server with `false` default value and adapt demo apps to use `allowSelfSigned: true`
- Currently, disconnecting dapps does not work correctly. I didn’t have time to find why, but if you manage to find some fix - much appreciated.
- In `func didReceive(event: WebSocketEvent, client: WebSocket)` I would add support for `ping` and `pong` cases. On `ping` we should write data as in timer: `self?.socket.write(ping: Data())`
- It seems that Timer does not work correctly. I could not find in console logged messages. Is it the same for you?
Everywhere in `didReceive` and `didDisconnect` we need to change `WC: ==>` to `WC: <==` as these are incoming messages.

**Comment by DtechLabs** [comment]
Hmm.  Ok. I'll try. But not yearly than this weekend

**Comment by sche** [comment]
Hi @DtechLabs ,
How are you doing? To manage expectations, I will not have time in the next couple of months to bring this PR to the production-ready state and implement all mentioned above features. But if you or someone else will finish it, I am happy to test it and release a new library version.
There is one more similar PR that is open.
If I have time, I will try to finish it myself, but for now, I am not very optimistic about it :(

**Comment by DtechLabs** [comment]
Hi @sche,
I took a look at another PR. It is the same as mine. I'm yet overhead with the release of a new future in my project, but think the second half of next week will have a little free time to make necessary changes in my PR.
If nobody does it yearly.

**Comment by sche** [comment]
@zulkis thank you for the contribution!
My colleague @DmitryBespalov is taking a look and hopefully, we will merge your changes soon.

**Comment by DmitryBespalov** [comment]
Thank you, I'm closing this PR in lieu of #84

**Pull request closed without merging**
