### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Based on the #81 - I removed reconnection of sockets upon uikit events (will handle that in a separate PR).

@zulkis please take a look

### CODE REVIEW

**Comment by zulkis** [comment]
@DmitryBespalov Didn't run it, but that compiles in my head. 👍

**Comment by JulienLevallois** [comment]
The 1.6.0 have theses changes ? Because I stil have the websockets error with Starscream
Thanks

**Comment by zulkis** [comment]
@JulienLevallois no, it does not. This MR is a "patch" for 1.6.0 as one could see in MR changes.

**Comment by DmitryBespalov** [comment]
@zulkis I've run this with our app and it worked just fine

**Comment by DmitryBespalov** [comment]
I moved example apps to a separate repository where I'll update them separately.

**Pull request merged**
